Map<String, String> hostelCodeMap = {
  'Azad Bhawan': 'AZ',
  'Cautley Bhawan': 'CB',
  'Ganga Bhawan': 'GA',
  'Govind Bhawan': 'GB',
  'Indira Bhawan': 'IB',
  'Jawahar Bhawan': 'JB',
  'Kasturba Bhawan': 'KB',
  'Malviya Bhawan': 'MB',
  'Radhakrishnan Bhawan': 'RKB',
  'Rajendra Bhawan': 'RJB',
  'Rajiv Bhawan': 'RB',
  'Ravindra Bhawan': 'RV',
  'Sarojini Bhawan': 'SB',
  'Vigyan Kunj': 'VK',
  'Development Government': 'DVG',
  'Development Private': 'DVP',
};
